package com.archeon.daysoff.business.util

object ErrorUtil {
	const val ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN"

	const val UNKNOWN_USER = "UNKNOWN_USER"
	const val UNKNOWN_TEAM = "UNKNOWN_TEAM"
	const val UNKNOWN_LEAVE = "UNKNOWN_LEAVE"
	const val UNKNOWN_SETTINGS = "UNKNOWN_SETTINGS"

	const val ONLY_DRAFT_CAN_BE_SUBMITTED = "ONLY_DRAFT_CAN_BE_SUBMITTED"
	const val ONLY_SUBMITTED_OR_REJECTED_CAN_BE_SET_BACK_AS_DRAFT = "ONLY_SUBMITTED_OR_REJECTED_CAN_BE_SET_BACK_AS_DRAFT"
	const val A_VALID_REQUEST_EXISTS_IN_THE_PERIOD = "A_VALID_REQUEST_EXISTS_IN_THE_PERIOD"

	const val YOU_CAN_ONLY_SUBMIT_LEAVE_IN_YOUR_TEAM = "YOU_CAN_ONLY_SUBMIT_LEAVE_IN_YOUR_TEAM"
	const val YOU_CAN_ONLY_UPDATE_LEAVE_IN_YOUR_TEAM = "YOU_CAN_ONLY_UPDATE_LEAVE_IN_YOUR_TEAM"
	const val YOU_CAN_ONLY_VALIDATE_LEAVE_REQUEST_IN_YOUR_TEAM = "YOU_CAN_ONLY_SUBMIT_FOR_USER_IN_YOUR_TEAM"
	const val YOU_CAN_ONLY_CREATE_LEAVE_REQUEST_IN_YOUR_TEAM = "YOU_CAN_ONLY_CREATE_FOR_USER_IN_YOUR_TEAM"
	const val YOU_CAN_ONLY_REFUSE_LEAVE_REQUEST_IN_YOUR_TEAM = "YOU_CAN_ONLY_REFUSE_FOR_USER_IN_YOUR_TEAM"
	const val YOU_CAN_ONLY_SET_AS_DRAFT_LEAVE_REQUEST_IN_YOUR_TEAM = "YOU_CAN_ONLY_SET_AS_DRAFT_FOR_USER_IN_YOUR_TEAM"

	const val YOU_CAN_ONLY_SUBMIT_LEAVE_REQUEST_FOR_YOURSELF = "YOU_CAN_ONLY_SUBMIT_LEAVE_REQUEST_FOR_YOURSELF"
	const val YOU_CAN_ONLY_UPDATE_LEAVE_REQUEST_FOR_YOURSELF = "YOU_CAN_ONLY_UPDATE_LEAVE_REQUEST_FOR_YOURSELF"
	const val YOU_CAN_ONLY_CREATE_LEAVE_REQUEST_FOR_YOURSELF = "YOU_CAN_ONLY_CREATE_LEAVE_REQUEST_FOR_YOURSELF"
	const val YOU_CAN_ONLY_SET_AS_DRAFT_LEAVE_REQUEST_FOR_YOURSELF = "YOU_CAN_ONLY_SET_AS_DRAFT_LEAVE_REQUEST_FOR_YOURSELF"

	const val INVALID_TOKEN = "INVALID_TOKEN"
	const val BAD_AUTHENTICATION_REQUEST = "BAD_AUTHENTICATION_REQUEST"

	const val MANDATORY_FIELD = "MANDATORY_FIELD"
	const val TEAM_ALREADY_EXISTS = "TEAM_ALREADY_EXISTS"
	const val TEAM_WITH_USERS = "TEAM_WITH_USERS"
	const val USER_EMAIL_ALREADY_USED = "USER_EMAIL_ALREADY_USED"
	const val USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

	const val YOU_CAN_ONLY_UPDATE_DRAFT_LEAVE_REQUEST = "YOU_CAN_ONLY_UPDATE_DRAFT_LEAVE_REQUEST"
}
